// generated by freezedts, do not edit

export type AddressParams = {
  street: string;
  city: string;
  zip?: string | undefined;
};

export abstract class $Address {
  readonly street!: string;
  readonly city!: string;
  readonly zip!: string | undefined;

  constructor(params: AddressParams) {
    this.street = params.street;
    this.city = params.city;
    this.zip = params.zip;
    Object.freeze(this);
  }
}

export type ContactParams = {
  name: string;
  email: string;
};

export abstract class $Contact {
  readonly name!: string;
  readonly email!: string;

  constructor(params: ContactParams) {
    this.name = params.name;
    this.email = params.email;
    Object.freeze(this);
  }
}
