import { describe, it, expect } from 'bun:test';
import { emitFreezedFile } from './emitter.js';
import type { ParsedFreezedClass } from './parser.js';

describe('emitFreezedFile', () => {
  it('generates header and runtime import', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('// generated by freezedts, do not edit');
    expect(output).toContain("import { createWithProxy } from 'freezedts/runtime'");
  });

  it('generates a base class with readonly properties and Object.freeze', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'firstName', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'lastName', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('export type PersonParams = {');
    expect(output).toContain('  firstName: string;');
    expect(output).toContain('  lastName: string;');
    expect(output).toContain('  age: number;');
    expect(output).toContain('export abstract class $Person {');
    expect(output).toContain('  readonly firstName!: string;');
    expect(output).toContain('  readonly lastName!: string;');
    expect(output).toContain('  readonly age!: number;');
    expect(output).toContain('  constructor(params: PersonParams) {');
    expect(output).toContain('    this.firstName = params.firstName;');
    expect(output).toContain('    Object.freeze(this);');
  });

  it('generates a With type and getter instead of with() method', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // With type — no @freezed properties, so simple callable
    expect(output).toContain('export type PersonWith<Self> = {');
    expect(output).toContain('  (overrides: Partial<PersonParams>): Self;');
    // Getter
    expect(output).toContain('get with(): PersonWith<this>');
    expect(output).toContain('return createWithProxy(this)');
    // Old method gone
    expect(output).not.toContain('with(overrides:');
  });

  it('generates With type with nested members for @freezed properties', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Inner',
        generatedClassName: '$Inner',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
      {
        className: 'Outer',
        generatedClassName: '$Outer',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'inner', type: 'Inner', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: true },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // Outer's With type includes inner chain
    expect(output).toContain('export type OuterWith<Self> = {');
    expect(output).toContain('  (overrides: Partial<OuterParams>): Self;');
    expect(output).toContain('  inner: InnerWith<Self>;');
    // Inner's With type has no nested members
    expect(output).toContain('export type InnerWith<Self> = {');
  });

  it('replaces @freezed property types with $ClassName in params and readonly', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Inner',
        generatedClassName: '$Inner',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
      {
        className: 'Outer',
        generatedClassName: '$Outer',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'inner', type: 'Inner', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: true },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // Params type uses $Inner
    expect(output).toContain('  inner: $Inner;');
    // Readonly field uses $Inner
    expect(output).toContain('  readonly inner!: $Inner;');
  });

  it('marks optional params with ? in the params type', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Config',
        generatedClassName: '$Config',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'host', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'port', type: 'number', optional: true, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  host: string;');
    expect(output).toContain('  port?: number;');
    expect(output).toContain('  readonly port!: number;');
  });

  it('makes hasDefault properties optional in params type', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasDefaults: true, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'count', type: 'number', optional: false, hasDefault: true, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  name: string;');
    expect(output).toContain('  count?: number;');
  });

  it('generates per-field default blocks when hasDefaults is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasDefaults: true,
        hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'count', type: 'number', optional: false, hasDefault: true, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain("Symbol.for('freezedts:options')");
    expect(output).toContain('const resolved = { ...params } as Required<CounterParams>;');
    // Per-field default block, no generic loop
    expect(output).toContain('(resolved as any).count === undefined');
    expect(output).toContain('__fields.count.default');
    // No assert code emitted
    expect(output).not.toContain('.assert');
    // No generic loop
    expect(output).not.toContain('Object.entries');
    expect(output).toContain('this.name = resolved.name;');
    expect(output).toContain('this.count = resolved.count;');
  });

  it('generates per-field assert blocks when hasAsserts is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Email',
        generatedClassName: '$Email',
        hasDefaults: false,
        hasAsserts: true,
        equalityMode: 'deep',
        properties: [
          { name: 'address', type: 'string', optional: false, hasDefault: false, hasAssert: true, hasMessage: true, isFreezed: false },
          { name: 'subject', type: 'string', optional: false, hasDefault: false, hasAssert: true, hasMessage: false, isFreezed: false },
          { name: 'body', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // Assert with custom message
    expect(output).toContain('__fields.address.assert((resolved as any).address)');
    expect(output).toContain('__fields.address.message');
    // Assert without message — template literal fallback
    expect(output).toContain('__fields.subject.assert((resolved as any).subject)');
    expect(output).toContain("Assertion failed for");
    // No default code
    expect(output).not.toContain('.default');
    // body has no assert — no block for it
    expect(output).not.toContain('__fields.body');
  });

  it('generates if/else-if block when property has both default and assert', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Config',
        generatedClassName: '$Config',
        hasDefaults: true,
        hasAsserts: true,
        equalityMode: 'deep',
        properties: [
          { name: 'port', type: 'number', optional: false, hasDefault: true, hasAssert: true, hasMessage: true, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // if/else if pattern: default branch, then assert branch
    expect(output).toContain('(resolved as any).port === undefined');
    expect(output).toContain('__fields.port.default');
    expect(output).toContain('} else if (!__fields.port.assert');
    expect(output).toContain('__fields.port.message');
  });

  it('omits processing block when hasFieldConfig is false', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Simple',
        generatedClassName: '$Simple',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).not.toContain('resolved');
    expect(output).toContain('this.value = params.value;');
  });

  it('strips | undefined from readonly type when hasDefault is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasDefaults: true, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'count', type: 'number | undefined', optional: true, hasDefault: true, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  readonly count!: number;');
    expect(output).not.toContain('readonly count!: number | undefined');
    expect(output).toContain('  count?: number | undefined;');
  });

  it('generates multiple classes in one file', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [{ name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false }],
      },
      {
        className: 'Child',
        generatedClassName: '$Child',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'parentName', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('export abstract class $Person {');
    expect(output).toContain('export abstract class $Child {');
    expect(output).toContain('export type PersonParams = {');
    expect(output).toContain('export type ChildParams = {');
    expect(output).toContain('export type PersonWith<Self>');
    expect(output).toContain('export type ChildWith<Self>');
  });

  it('generates deepEqual helper when non-primitive properties exist', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Team',
        generatedClassName: '$Team',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'members', type: 'string[]', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('deepEqual');
  });

  it('generates equals() method with deep comparison', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).toContain('other instanceof $Person');
    expect(output).toContain('this.name === other.name');
    expect(output).toContain('Object.is(this.age, other.age)');
  });

  it('generates equals() with === for shallow mode', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Config',
        generatedClassName: '$Config',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'shallow',
        properties: [
          { name: 'host', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'port', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).toContain('other instanceof $Config');
    expect(output).toContain('this.host === other.host');
    expect(output).toContain('this.port === other.port');
    expect(output).not.toContain('deepEqual(this.host');
  });

  it('generates equals() using .equals() for @freezed properties in shallow mode', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Inner',
        generatedClassName: '$Inner',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
      {
        className: 'Outer',
        generatedClassName: '$Outer',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'shallow',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'inner', type: 'Inner', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: true },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('this.inner.equals(other.inner)');
    expect(output).toContain('this.name === other.name');
  });

  it('generates toString() method with all properties', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'firstName', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'lastName', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('toString(): string');
    expect(output).toContain('${this.constructor.name}');
    expect(output).toContain('firstName: ${this.firstName}');
    expect(output).toContain('lastName: ${this.lastName}');
    expect(output).toContain('age: ${this.age}');
  });

  it('generates toString() for class with single property', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Tag',
        generatedClassName: '$Tag',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('toString(): string');
    expect(output).toContain('value: ${this.value}');
  });

  it('generates toString() for class with no properties', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Empty',
        generatedClassName: '$Empty',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('toString(): string');
    expect(output).toContain('`${this.constructor.name}()`');
  });

  it('imports deepFreeze when non-primitive properties exist', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Team',
        generatedClassName: '$Team',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'members', type: 'string[]', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain("from 'freezedts/runtime'");
    expect(output).toContain('deepFreeze');
  });

  it('calls deepFreeze on each property before Object.freeze(this)', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Team',
        generatedClassName: '$Team',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'members', type: 'string[]', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('this.name = params.name;');
    expect(output).toContain('this.members = deepFreeze(params.members)');
  });

  it('uses deepFreeze with resolved params when hasDefaults', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Config',
        generatedClassName: '$Config',
        hasDefaults: true,
        hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'count', type: 'number', optional: false, hasDefault: true, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'items', type: 'string[]', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('this.items = deepFreeze(resolved.items)');
  });

  it('omits WithType, with getter, and createWithProxy helper when copyWith is false', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        copyWith: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('PersonWith<');
    expect(output).not.toContain('get with()');
    expect(output).not.toContain('createWithProxy');
    // Should still have equals and toString
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).toContain('toString(): string');
  });

  it('includes WithType and with getter when copyWith is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        copyWith: true,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('PersonWith<Self>');
    expect(output).toContain('get with()');
    expect(output).toContain('createWithProxy');
  });

  it('includes WithType and with getter when copyWith is undefined (default)', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('PersonWith<Self>');
    expect(output).toContain('get with()');
    expect(output).toContain('createWithProxy');
  });

  it('emits createWithProxy helper only when at least one class has copyWith enabled', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'NoCopy',
        generatedClassName: '$NoCopy',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        copyWith: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
      {
        className: 'WithCopy',
        generatedClassName: '$WithCopy',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        copyWith: true,
        properties: [
          { name: 'value', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    // Helper emitted because WithCopy needs it
    expect(output).toContain('createWithProxy');
    // NoCopy still has no with getter
    expect(output).not.toContain('NoCopyWith<');
    // WithCopy has with getter
    expect(output).toContain('WithCopyWith<Self>');
  });

  it('omits equals() method and deepEqual helper when equal is false', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        equal: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('equals(other: unknown)');
    expect(output).not.toContain('deepEqual');
    // Should still have with and toString
    expect(output).toContain('get with()');
    expect(output).toContain('toString(): string');
  });

  it('includes equals() method when equal is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        equal: true,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).not.toContain('deepEqual');
    expect(output).toContain('this.name === other.name');
  });

  it('includes equals() method when equal is undefined (default)', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).not.toContain('deepEqual');
    expect(output).toContain('this.name === other.name');
  });

  it('omits both with() and equals() when both disabled', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Minimal',
        generatedClassName: '$Minimal',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        copyWith: false,
        equal: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('get with()');
    expect(output).not.toContain('MinimalWith<');
    expect(output).not.toContain('equals(other: unknown)');
    expect(output).not.toContain('createWithProxy');
    expect(output).not.toContain('deepEqual');
    // Still has: header, params type, class, constructor, toString
    expect(output).toContain('// generated by freezedts, do not edit');
    expect(output).not.toContain('deepFreeze');
    expect(output).toContain('export type MinimalParams');
    expect(output).toContain('export abstract class $Minimal');
    expect(output).toContain('Object.freeze(this)');
    expect(output).toContain('toString(): string');
  });

  it('omits toString() method when toString is false', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        toString: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('toString(): string');
    // Should still have with and equals
    expect(output).toContain('get with()');
    expect(output).toContain('equals(other: unknown): boolean');
  });

  it('includes toString() method when toString is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        toString: true,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('toString(): string');
  });

  it('includes toString() method when toString is undefined (default)', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('toString(): string');
  });

  it('omits all methods when copyWith, equal, and toString are all disabled', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Bare',
        generatedClassName: '$Bare',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        copyWith: false,
        equal: false,
        toString: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('get with()');
    expect(output).not.toContain('equals(other: unknown)');
    expect(output).not.toContain('toString(): string');
    // Still has: header, params type, class, constructor
    expect(output).toContain('// generated by freezedts, do not edit');
    expect(output).toContain('export type BareParams');
    expect(output).toContain('export abstract class $Bare');
    expect(output).toContain('Object.freeze(this)');
  });

  it('omits deepFreeze when all properties are primitive types', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false,
        hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('deepFreeze');
  });

  it('omits deepFreeze when optional primitives have | undefined suffix', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasDefaults: true,
        hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'count', type: 'number | undefined', optional: true, hasDefault: true, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('deepFreeze');
    expect(output).toContain('this.count = resolved.count;');
  });

  it('generates equals() with correct indentation for multi-property deep comparison', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Pair',
        generatedClassName: '$Pair',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'a', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'b', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    // Must NOT have extra leading spaces between "return" and the first comparison
    expect(output).toContain('return this.a === other.a');
    expect(output).not.toContain('return     this.a');
  });

  it('imports deepEqual when non-primitive properties exist in deep mode', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Simple',
        generatedClassName: '$Simple',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'data', type: 'Record<string, unknown>', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain("import { createWithProxy, deepEqual, deepFreeze } from 'freezedts/runtime'");
  });

  it('uses Object.is for number in deep mode', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Simple',
        generatedClassName: '$Simple',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'data', type: 'Record<string, unknown>', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('Object.is(this.value, other.value)');
  });

  it('generates null-safe equals() for optional @freezed properties in shallow mode', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Inner',
        generatedClassName: '$Inner',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
      {
        className: 'Outer',
        generatedClassName: '$Outer',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'shallow',
        properties: [
          { name: 'inner', type: 'Inner', optional: true, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: true },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    // Must not call .equals() directly on a potentially null property
    expect(output).not.toMatch(/return\s+this\.inner\.equals\(other\.inner\)/);
    // Should include null guard
    expect(output).toContain('this.inner != null');
  });

  it('emits deepEqual helper only when at least one class has equal enabled', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'NoEq',
        generatedClassName: '$NoEq',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        equal: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
      {
        className: 'WithEq',
        generatedClassName: '$WithEq',
        hasDefaults: false, hasAsserts: false,
        equalityMode: 'deep',
        equal: true,
        properties: [
          { name: 'items', type: 'string[]', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('deepEqual');
    expect(output).toContain('$WithEq');
  });

  it('generates === for string/boolean and Object.is for number in deep equality mode', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Record',
        generatedClassName: '$Record',
        hasDefaults: false,
        hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'label', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'count', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'active', type: 'boolean', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'tags', type: 'string[]', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('this.label === other.label');
    expect(output).toContain('Object.is(this.count, other.count)');
    expect(output).toContain('this.active === other.active');
    expect(output).toContain('deepEqual(this.tags, other.tags)');
  });

  it('omits deepEqual helper when all deep-mode properties are primitive', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasDefaults: false,
        hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('deepEqual');
    expect(output).toContain('this.name === other.name');
    expect(output).toContain('Object.is(this.age, other.age)');
  });

  it('uses Object.is for number | undefined in deep equality mode', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasDefaults: true,
        hasAsserts: false,
        equalityMode: 'deep',
        properties: [
          { name: 'count', type: 'number | undefined', optional: true, hasDefault: true, hasAssert: false, hasMessage: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('Object.is(this.count, other.count)');
    expect(output).not.toContain('deepEqual');
  });
});
