import type { ParsedFreezedClass } from './parser.js';

const HEADER = `// generated by freezedts, do not edit\n`;

export function emitFreezedFile(classes: ParsedFreezedClass[]): string {
  const needsWith = classes.some(c => c.copyWith !== false);
  const needsDeepEqual = classes.some(c =>
    c.equal !== false && c.equalityMode === 'deep' && c.properties.some(p => {
      const baseType = p.type.replace(/\s*\|\s*undefined$/, '').trim();
      return !PRIMITIVE_TYPES.has(baseType);
    })
  );
  const needsFreeze = classes.some(c =>
    c.properties.some(p => {
      const baseType = p.type.replace(/\s*\|\s*undefined$/, '').trim();
      return !PRIMITIVE_TYPES.has(baseType);
    })
  );

  const runtimeImports: string[] = [];
  if (needsWith) runtimeImports.push('createWithProxy');
  if (needsDeepEqual) runtimeImports.push('deepEqual');
  if (needsFreeze) runtimeImports.push('deepFreeze');

  const importLine = runtimeImports.length > 0
    ? `\nimport { ${runtimeImports.join(', ')} } from 'freezedts/runtime';\n`
    : '';

  const sections = classes.map(emitClass);
  return HEADER + importLine + '\n' + sections.join('\n\n') + '\n';
}

const PRIMITIVE_TYPES = new Set(['string', 'number', 'boolean', 'bigint']);

function emitClass(cls: ParsedFreezedClass): string {
  const paramsType = emitParamsType(cls);
  const parts = [paramsType];

  if (cls.copyWith !== false) {
    parts.push(emitWithType(cls));
  }

  parts.push(emitClassBody(cls));
  return parts.join('\n\n');
}

function emitParamsType(cls: ParsedFreezedClass): string {
  const fields = cls.properties
    .map((p) => {
      const optional = p.optional || p.hasDefault;
      const type = p.type;
      return `  ${p.name}${optional ? '?' : ''}: ${type};`;
    })
    .join('\n');
  return `export type ${cls.className}Params = {\n${fields}\n};`;
}

function emitWithType(cls: ParsedFreezedClass): string {
  const freezedProps = cls.properties.filter(p => p.isFreezed);
  const members = freezedProps
    .map(p => `  ${p.name}: ${p.type.replace(/\s*\|\s*undefined$/, '').trim()}With<Self>;`)
    .join('\n');
  const callSig = `  (overrides: Partial<${cls.className}Params>): Self;`;
  if (freezedProps.length === 0) {
    return `export type ${cls.className}With<Self> = {\n${callSig}\n};`;
  }
  return `export type ${cls.className}With<Self> = {\n${callSig}\n${members}\n};`;
}

function emitClassBody(cls: ParsedFreezedClass): string {
  const readonlyFields = cls.properties
    .map((p) => {
      let type = p.type;
      if (p.hasDefault) type = type.replace(/ \| undefined$/, '');
      return `  readonly ${p.name}!: ${type};`;
    })
    .join('\n');

  const paramsVar = (cls.hasDefaults || cls.hasAsserts) ? 'resolved' : 'params';

  const fieldConfigBlock = (cls.hasDefaults || cls.hasAsserts)
    ? emitFieldConfigBlock(cls)
    : '';

  const assignments = cls.properties
    .map((p) => {
      const baseType = p.type.replace(/\s*\|\s*undefined$/, '').trim();
      if (PRIMITIVE_TYPES.has(baseType)) {
        return `    this.${p.name} = ${paramsVar}.${p.name};`;
      }
      return `    this.${p.name} = deepFreeze(${paramsVar}.${p.name});`;
    })
    .join('\n');

  const methods: string[] = [];
  if (cls.copyWith !== false) methods.push(emitWithGetter(cls));
  if (cls.equal !== false) methods.push(emitEqualsMethod(cls));
  if (cls.toString !== false) methods.push(emitToStringMethod(cls));

  return `export abstract class ${cls.generatedClassName} {
${readonlyFields}

  constructor(params: ${cls.className}Params) {
${fieldConfigBlock}${assignments}
    Object.freeze(this);
  }

${methods.join('\n\n')}
}`;
}

function emitFieldConfigBlock(cls: ParsedFreezedClass): string {
  const lines = [
    `    const __fields = (new.target as any)[Symbol.for('freezedts:options')]?.fields ?? {};`,
    `    const resolved = { ...params } as Required<${cls.className}Params>;`,
  ];

  for (const p of cls.properties) {
    if (p.hasDefault && p.hasAssert) {
      const errorExpr = p.hasMessage
        ? `__fields.${p.name}.message`
        : `\`Assertion failed for '\${new.target.name}.${p.name}'\``;
      lines.push(`    if ((resolved as any).${p.name} === undefined) {`);
      lines.push(`      (resolved as any).${p.name} = __fields.${p.name}.default;`);
      lines.push(`    } else if (!__fields.${p.name}.assert((resolved as any).${p.name})) {`);
      lines.push(`      throw new Error(${errorExpr});`);
      lines.push(`    }`);
    } else if (p.hasDefault) {
      lines.push(`    if ((resolved as any).${p.name} === undefined) {`);
      lines.push(`      (resolved as any).${p.name} = __fields.${p.name}.default;`);
      lines.push(`    }`);
    } else if (p.hasAssert) {
      const errorExpr = p.hasMessage
        ? `__fields.${p.name}.message`
        : `\`Assertion failed for '\${new.target.name}.${p.name}'\``;
      lines.push(`    if (!__fields.${p.name}.assert((resolved as any).${p.name})) {`);
      lines.push(`      throw new Error(${errorExpr});`);
      lines.push(`    }`);
    }
  }

  return lines.join('\n') + '\n';
}

function emitWithGetter(cls: ParsedFreezedClass): string {
  return `  get with(): ${cls.className}With<this> {
    return createWithProxy(this);
  }`;
}

function emitToStringMethod(cls: ParsedFreezedClass): string {
  const parts = cls.properties
    .map((p) => `${p.name}: \${this.${p.name}}`)
    .join(', ');
  return `  toString(): string {
    return \`\${this.constructor.name}(${parts})\`;
  }`;
}

function emitEqualsMethod(cls: ParsedFreezedClass): string {
  const comparisons = cls.properties.map((p) => {
    if (cls.equalityMode === 'deep') {
      const baseType = p.type.replace(/\s*\|\s*undefined$/, '').trim();
      if (baseType === 'number') {
        return `Object.is(this.${p.name}, other.${p.name})`;
      }
      if (PRIMITIVE_TYPES.has(baseType)) {
        return `this.${p.name} === other.${p.name}`;
      }
      return `deepEqual(this.${p.name}, other.${p.name})`;
    }
    if (p.isFreezed) {
      if (p.optional) {
        return `(this.${p.name} === other.${p.name} || (this.${p.name} != null && other.${p.name} != null && this.${p.name}.equals(other.${p.name})))`;
      }
      return `this.${p.name}.equals(other.${p.name})`;
    }
    return `this.${p.name} === other.${p.name}`;
  });

  const returnExpr = comparisons.length === 0
    ? 'true'
    : comparisons.join(' &&\n      ');

  return `  equals(other: unknown): boolean {
    if (this === other) return true;
    if (!(other instanceof ${cls.generatedClassName})) return false;
    return ${returnExpr};
  }`;
}
