// generated by freezedts, do not edit

export type AddressParams = {
  street: string;
  city: string;
  zip?: string | undefined;
};

export abstract class $Address {
  readonly street!: string;
  readonly city!: string;
  readonly zip!: string | undefined;

  constructor(params: AddressParams) {
    this.street = params.street;
    this.city = params.city;
    this.zip = params.zip;
    Object.freeze(this);
  }

  with(overrides: Partial<AddressParams>): this {
    const Ctor = this.constructor as new (params: AddressParams) => this;
    return new Ctor({
      street: this.street,
      city: this.city,
      zip: this.zip,
      ...overrides,
    });
  }
}

export type ContactParams = {
  name: string;
  email: string;
};

export abstract class $Contact {
  readonly name!: string;
  readonly email!: string;

  constructor(params: ContactParams) {
    this.name = params.name;
    this.email = params.email;
    Object.freeze(this);
  }

  with(overrides: Partial<ContactParams>): this {
    const Ctor = this.constructor as new (params: ContactParams) => this;
    return new Ctor({
      name: this.name,
      email: this.email,
      ...overrides,
    });
  }
}
