// generated by freezedts, do not edit

export type PersonParams = {
  firstName: string;
  lastName: string;
  age: number;
};

export abstract class $Person {
  readonly firstName!: string;
  readonly lastName!: string;
  readonly age!: number;

  constructor(params: PersonParams) {
    this.firstName = params.firstName;
    this.lastName = params.lastName;
    this.age = params.age;
    Object.freeze(this);
  }
}
