import type { ParsedFreezedClass, ParsedProperty } from './parser.js';

const HEADER = `// generated by freezedts, do not edit\n`;

export function emitFreezedFile(classes: ParsedFreezedClass[]): string {
  const sections = classes.map(emitClass);
  return HEADER + '\n' + sections.join('\n\n') + '\n';
}

function emitClass(cls: ParsedFreezedClass): string {
  const paramsType = emitParamsType(cls);
  const classBody = emitClassBody(cls);
  return paramsType + '\n\n' + classBody;
}

function emitParamsType(cls: ParsedFreezedClass): string {
  const fields = cls.properties
    .map((p) => `  ${p.name}${p.optional ? '?' : ''}: ${p.type};`)
    .join('\n');
  return `export type ${cls.className}Params = {\n${fields}\n};`;
}

function emitClassBody(cls: ParsedFreezedClass): string {
  const readonlyFields = cls.properties
    .map((p) => `  readonly ${p.name}!: ${p.type};`)
    .join('\n');

  const assignments = cls.properties
    .map((p) => `    this.${p.name} = params.${p.name};`)
    .join('\n');

  return `export abstract class ${cls.generatedClassName} {
${readonlyFields}

  constructor(params: ${cls.className}Params) {
${assignments}
    Object.freeze(this);
  }
}`;
}
