import { describe, it, expect } from 'bun:test';
import { emitFreezedFile } from './emitter.js';
import type { ParsedFreezedClass } from './parser.js';

describe('emitFreezedFile', () => {
  it('generates header and deep copy helper', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('// generated by freezedts, do not edit');
    expect(output).toContain('const __freezedWith');
    expect(output).toContain("Symbol.for('freezedts:options')");
    expect(output).toContain('new Proxy');
  });

  it('generates a base class with readonly properties and Object.freeze', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'firstName', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'lastName', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('export type PersonParams = {');
    expect(output).toContain('  firstName: string;');
    expect(output).toContain('  lastName: string;');
    expect(output).toContain('  age: number;');
    expect(output).toContain('export abstract class $Person {');
    expect(output).toContain('  readonly firstName!: string;');
    expect(output).toContain('  readonly lastName!: string;');
    expect(output).toContain('  readonly age!: number;');
    expect(output).toContain('  constructor(params: PersonParams) {');
    expect(output).toContain('    this.firstName = __freezedDeepFreeze(params.firstName);');
    expect(output).toContain('    Object.freeze(this);');
  });

  it('generates a With type and getter instead of with() method', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // With type — no @freezed properties, so simple callable
    expect(output).toContain('export type PersonWith<Self> = {');
    expect(output).toContain('  (overrides: Partial<PersonParams>): Self;');
    // Getter
    expect(output).toContain('get with(): PersonWith<this>');
    expect(output).toContain('return __freezedWith(this)');
    // Old method gone
    expect(output).not.toContain('with(overrides:');
  });

  it('generates With type with nested members for @freezed properties', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Inner',
        generatedClassName: '$Inner',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
      {
        className: 'Outer',
        generatedClassName: '$Outer',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'inner', type: 'Inner', optional: false, hasDefault: false, isFreezed: true },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // Outer's With type includes inner chain
    expect(output).toContain('export type OuterWith<Self> = {');
    expect(output).toContain('  (overrides: Partial<OuterParams>): Self;');
    expect(output).toContain('  inner: InnerWith<Self>;');
    // Inner's With type has no nested members
    expect(output).toContain('export type InnerWith<Self> = {');
  });

  it('replaces @freezed property types with $ClassName in params and readonly', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Inner',
        generatedClassName: '$Inner',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
      {
        className: 'Outer',
        generatedClassName: '$Outer',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'inner', type: 'Inner', optional: false, hasDefault: false, isFreezed: true },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // Params type uses $Inner
    expect(output).toContain('  inner: $Inner;');
    // Readonly field uses $Inner
    expect(output).toContain('  readonly inner!: $Inner;');
  });

  it('marks optional params with ? in the params type', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Config',
        generatedClassName: '$Config',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'host', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'port', type: 'number', optional: true, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  host: string;');
    expect(output).toContain('  port?: number;');
    expect(output).toContain('  readonly port!: number;');
  });

  it('makes hasDefault properties optional in params type', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasFieldConfig: true,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'count', type: 'number', optional: false, hasDefault: true, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  name: string;');
    expect(output).toContain('  count?: number;');
  });

  it('generates field config processing block when hasFieldConfig is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasFieldConfig: true,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'count', type: 'number', optional: false, hasDefault: true, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain("Symbol.for('freezedts:options')");
    expect(output).toContain('const resolved = { ...params } as Required<CounterParams>;');
    expect(output).toContain("if ('default' in config");
    expect(output).toContain('config.assert');
    expect(output).toContain('this.name = __freezedDeepFreeze(resolved.name);');
    expect(output).toContain('this.count = __freezedDeepFreeze(resolved.count);');
  });

  it('omits processing block when hasFieldConfig is false', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Simple',
        generatedClassName: '$Simple',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).not.toContain('resolved');
    expect(output).toContain('this.value = __freezedDeepFreeze(params.value);');
  });

  it('strips | undefined from readonly type when hasDefault is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasFieldConfig: true,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'count', type: 'number | undefined', optional: true, hasDefault: true, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  readonly count!: number;');
    expect(output).not.toContain('readonly count!: number | undefined');
    expect(output).toContain('  count?: number | undefined;');
  });

  it('generates multiple classes in one file', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [{ name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false }],
      },
      {
        className: 'Child',
        generatedClassName: '$Child',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'parentName', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('export abstract class $Person {');
    expect(output).toContain('export abstract class $Child {');
    expect(output).toContain('export type PersonParams = {');
    expect(output).toContain('export type ChildParams = {');
    expect(output).toContain('export type PersonWith<Self>');
    expect(output).toContain('export type ChildWith<Self>');
  });

  it('generates __freezedDeepEqual helper', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('__freezedDeepEqual');
  });

  it('generates equals() method with deep comparison', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).toContain('other instanceof $Person');
    expect(output).toContain('__freezedDeepEqual(this.name, other.name)');
    expect(output).toContain('__freezedDeepEqual(this.age, other.age)');
  });

  it('generates equals() with === for shallow mode', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Config',
        generatedClassName: '$Config',
        hasFieldConfig: false,
        equalityMode: 'shallow',
        properties: [
          { name: 'host', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'port', type: 'number', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).toContain('other instanceof $Config');
    expect(output).toContain('this.host === other.host');
    expect(output).toContain('this.port === other.port');
    expect(output).not.toContain('__freezedDeepEqual(this.host');
  });

  it('generates equals() using .equals() for @freezed properties in shallow mode', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Inner',
        generatedClassName: '$Inner',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
      {
        className: 'Outer',
        generatedClassName: '$Outer',
        hasFieldConfig: false,
        equalityMode: 'shallow',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'inner', type: 'Inner', optional: false, hasDefault: false, isFreezed: true },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('this.inner.equals(other.inner)');
    expect(output).toContain('this.name === other.name');
  });

  it('generates toString() method with all properties', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'firstName', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'lastName', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('toString(): string');
    expect(output).toContain('${this.constructor.name}');
    expect(output).toContain('firstName: ${this.firstName}');
    expect(output).toContain('lastName: ${this.lastName}');
    expect(output).toContain('age: ${this.age}');
  });

  it('generates toString() for class with single property', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Tag',
        generatedClassName: '$Tag',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('toString(): string');
    expect(output).toContain('value: ${this.value}');
  });

  it('generates toString() for class with no properties', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Empty',
        generatedClassName: '$Empty',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('toString(): string');
    expect(output).toContain('`${this.constructor.name}()`');
  });

  it('generates __freezedDeepFreeze helper', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Team',
        generatedClassName: '$Team',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'members', type: 'string[]', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('const __freezedDeepFreeze');
    expect(output).toContain('Object.freeze');
  });

  it('calls __freezedDeepFreeze on each property before Object.freeze(this)', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Team',
        generatedClassName: '$Team',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'members', type: 'string[]', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('this.name = __freezedDeepFreeze(params.name)');
    expect(output).toContain('this.members = __freezedDeepFreeze(params.members)');
  });

  it('uses __freezedDeepFreeze with resolved params when hasFieldConfig', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Config',
        generatedClassName: '$Config',
        hasFieldConfig: true,
        equalityMode: 'deep',
        properties: [
          { name: 'items', type: 'string[]', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('this.items = __freezedDeepFreeze(resolved.items)');
  });

  it('omits WithType, with getter, and __freezedWith helper when copyWith is false', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        copyWith: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('PersonWith<');
    expect(output).not.toContain('get with()');
    expect(output).not.toContain('__freezedWith');
    // Should still have equals and toString
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).toContain('toString(): string');
  });

  it('includes WithType and with getter when copyWith is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        copyWith: true,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('PersonWith<Self>');
    expect(output).toContain('get with()');
    expect(output).toContain('__freezedWith');
  });

  it('includes WithType and with getter when copyWith is undefined (default)', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('PersonWith<Self>');
    expect(output).toContain('get with()');
    expect(output).toContain('__freezedWith');
  });

  it('emits __freezedWith helper only when at least one class has copyWith enabled', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'NoCopy',
        generatedClassName: '$NoCopy',
        hasFieldConfig: false,
        equalityMode: 'deep',
        copyWith: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
      {
        className: 'WithCopy',
        generatedClassName: '$WithCopy',
        hasFieldConfig: false,
        equalityMode: 'deep',
        copyWith: true,
        properties: [
          { name: 'value', type: 'number', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    // Helper emitted because WithCopy needs it
    expect(output).toContain('__freezedWith');
    // NoCopy still has no with getter
    expect(output).not.toContain('NoCopyWith<');
    // WithCopy has with getter
    expect(output).toContain('WithCopyWith<Self>');
  });

  it('omits equals() method and __freezedDeepEqual helper when equal is false', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        equal: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('equals(other: unknown)');
    expect(output).not.toContain('__freezedDeepEqual');
    // Should still have with and toString
    expect(output).toContain('get with()');
    expect(output).toContain('toString(): string');
  });

  it('includes equals() method when equal is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        equal: true,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).toContain('__freezedDeepEqual');
  });

  it('includes equals() method when equal is undefined (default)', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        equalityMode: 'deep',
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('equals(other: unknown): boolean');
    expect(output).toContain('__freezedDeepEqual');
  });

  it('omits both with() and equals() when both disabled', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Minimal',
        generatedClassName: '$Minimal',
        hasFieldConfig: false,
        equalityMode: 'deep',
        copyWith: false,
        equal: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).not.toContain('get with()');
    expect(output).not.toContain('MinimalWith<');
    expect(output).not.toContain('equals(other: unknown)');
    expect(output).not.toContain('__freezedWith');
    expect(output).not.toContain('__freezedDeepEqual');
    // Still has: header, freeze helper, params type, class, constructor, toString
    expect(output).toContain('// generated by freezedts, do not edit');
    expect(output).toContain('__freezedDeepFreeze');
    expect(output).toContain('export type MinimalParams');
    expect(output).toContain('export abstract class $Minimal');
    expect(output).toContain('Object.freeze(this)');
    expect(output).toContain('toString(): string');
  });

  it('emits __freezedDeepEqual helper only when at least one class has equal enabled', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'NoEq',
        generatedClassName: '$NoEq',
        hasFieldConfig: false,
        equalityMode: 'deep',
        equal: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
      {
        className: 'WithEq',
        generatedClassName: '$WithEq',
        hasFieldConfig: false,
        equalityMode: 'deep',
        equal: true,
        properties: [
          { name: 'value', type: 'number', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('__freezedDeepEqual');
    expect(output).toContain('$WithEq');
  });
});
