import { describe, it, expect } from 'bun:test';
import { emitFreezedFile } from './emitter.js';
import type { ParsedFreezedClass } from './parser.js';

describe('emitFreezedFile', () => {
  it('generates a base class with readonly properties and Object.freeze', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        properties: [
          { name: 'firstName', type: 'string', optional: false },
          { name: 'lastName', type: 'string', optional: false },
          { name: 'age', type: 'number', optional: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);

    // Header
    expect(output).toContain('// generated by freezedts, do not edit');

    // Params type
    expect(output).toContain('export type PersonParams = {');
    expect(output).toContain('  firstName: string;');
    expect(output).toContain('  lastName: string;');
    expect(output).toContain('  age: number;');

    // Abstract class
    expect(output).toContain('export abstract class $Person {');
    expect(output).toContain('  readonly firstName!: string;');
    expect(output).toContain('  readonly lastName!: string;');
    expect(output).toContain('  readonly age!: number;');

    // Constructor assigns and freezes
    expect(output).toContain('  constructor(params: PersonParams) {');
    expect(output).toContain("    this.firstName = params.firstName;");
    expect(output).toContain("    this.lastName = params.lastName;");
    expect(output).toContain("    this.age = params.age;");
    expect(output).toContain('    Object.freeze(this);');
  });

  it('marks optional params with ? in the params type', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Config',
        generatedClassName: '$Config',
        properties: [
          { name: 'host', type: 'string', optional: false },
          { name: 'port', type: 'number', optional: true },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  host: string;');
    expect(output).toContain('  port?: number;');
    // readonly property is NOT optional — it always has a value after construction
    expect(output).toContain('  readonly port!: number;');
  });

  it('generates multiple classes in one file', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        properties: [{ name: 'name', type: 'string', optional: false }],
      },
      {
        className: 'Child',
        generatedClassName: '$Child',
        properties: [
          { name: 'name', type: 'string', optional: false },
          { name: 'parentName', type: 'string', optional: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('export abstract class $Person {');
    expect(output).toContain('export abstract class $Child {');
    expect(output).toContain('export type PersonParams = {');
    expect(output).toContain('export type ChildParams = {');
  });
});
