import type { ParsedFreezedClass } from './parser.js';

const HEADER = `// generated by freezedts, do not edit\n`;

export function emitFreezedFile(classes: ParsedFreezedClass[]): string {
  const needsWith = classes.some(c => c.copyWith !== false);
  const needsEqual = classes.some(c => c.equal !== false);

  const helpers: string[] = [];
  if (needsWith) helpers.push(emitDeepCopyHelper());
  if (needsEqual) helpers.push(emitDeepEqualHelper());
  helpers.push(emitDeepFreezeHelper());

  const sections = classes.map(emitClass);
  return HEADER + '\n' + helpers.join('\n\n') + '\n\n' + sections.join('\n\n') + '\n';
}

function emitDeepCopyHelper(): string {
  return `const __freezedWith = (() => {
  const OPTS = Symbol.for('freezedts:options');
  const isFz = (v: unknown): boolean =>
    v != null && typeof v === 'object' &&
    typeof (v as any).constructor === 'function' &&
    OPTS in (v as any).constructor;
  const copy = (obj: any, over: any): any => {
    const C = obj.constructor as new (p: any) => any;
    const p: any = {};
    for (const k of Object.keys(obj)) p[k] = (obj as any)[k];
    return new C({ ...p, ...over });
  };
  const deep = (root: any, path: string[], over: any): any => {
    if (!path.length) return copy(root, over);
    const [h, ...rest] = path;
    return copy(root, { [h]: deep(root[h], rest, over) });
  };
  const px = (root: any, path: string[]): any =>
    new Proxy((() => {}) as any, {
      apply: (_, __, a) => deep(root, path, a[0] ?? {}),
      get: (_, p) => {
        if (typeof p !== 'string') return undefined;
        let c: any = root;
        for (const s of path) c = c[s];
        return isFz(c[p]) ? px(root, [...path, p]) : undefined;
      },
    });
  return (instance: any) => px(instance, []);
})();`;
}

function emitDeepEqualHelper(): string {
  return `const __freezedDeepEqual = (a: unknown, b: unknown): boolean => {
  if (a === b) return true;
  if (a == null || b == null) return a === b;
  if (typeof a !== typeof b) return false;
  if (typeof a !== 'object') return false;
  if (typeof (a as any).equals === 'function' && a.constructor === b.constructor) {
    return (a as any).equals(b);
  }
  if (Array.isArray(a)) {
    if (!Array.isArray(b) || a.length !== b.length) return false;
    return a.every((v, i) => __freezedDeepEqual(v, (b as any[])[i]));
  }
  const keysA = Object.keys(a);
  const keysB = Object.keys(b as object);
  if (keysA.length !== keysB.length) return false;
  return keysA.every(k => __freezedDeepEqual((a as any)[k], (b as any)[k]));
};`;
}

function emitDeepFreezeHelper(): string {
  return `const __freezedDeepFreeze = <T>(value: T): T => {
  if (value == null || typeof value !== 'object') return value;
  if (Object.isFrozen(value)) return value;
  if (Array.isArray(value)) {
    for (let i = 0; i < value.length; i++) __freezedDeepFreeze(value[i]);
    Object.freeze(value);
    return value;
  }
  if (value instanceof Map) {
    const _throw = () => { throw new TypeError('Cannot mutate a frozen Map'); };
    value.set = _throw as any;
    value.delete = _throw as any;
    value.clear = _throw as any;
    value.forEach((v, k) => { __freezedDeepFreeze(k); __freezedDeepFreeze(v); });
    Object.freeze(value);
    return value;
  }
  if (value instanceof Set) {
    const _throw = () => { throw new TypeError('Cannot mutate a frozen Set'); };
    value.add = _throw as any;
    value.delete = _throw as any;
    value.clear = _throw as any;
    value.forEach((v) => __freezedDeepFreeze(v));
    Object.freeze(value);
    return value;
  }
  for (const key of Object.keys(value)) __freezedDeepFreeze((value as any)[key]);
  Object.freeze(value);
  return value;
};`;
}

function emitClass(cls: ParsedFreezedClass): string {
  const paramsType = emitParamsType(cls);
  const parts = [paramsType];

  if (cls.copyWith !== false) {
    parts.push(emitWithType(cls));
  }

  parts.push(emitClassBody(cls));
  return parts.join('\n\n');
}

function emitParamsType(cls: ParsedFreezedClass): string {
  const fields = cls.properties
    .map((p) => {
      const optional = p.optional || p.hasDefault;
      const type = p.isFreezed ? `$${p.type}` : p.type;
      return `  ${p.name}${optional ? '?' : ''}: ${type};`;
    })
    .join('\n');
  return `export type ${cls.className}Params = {\n${fields}\n};`;
}

function emitWithType(cls: ParsedFreezedClass): string {
  const freezedProps = cls.properties.filter(p => p.isFreezed);
  const members = freezedProps
    .map(p => `  ${p.name}: ${p.type}With<Self>;`)
    .join('\n');
  const callSig = `  (overrides: Partial<${cls.className}Params>): Self;`;
  if (freezedProps.length === 0) {
    return `export type ${cls.className}With<Self> = {\n${callSig}\n};`;
  }
  return `export type ${cls.className}With<Self> = {\n${callSig}\n${members}\n};`;
}

function emitClassBody(cls: ParsedFreezedClass): string {
  const readonlyFields = cls.properties
    .map((p) => {
      let type = p.isFreezed ? `$${p.type}` : p.type;
      if (p.hasDefault) type = type.replace(/ \| undefined$/, '');
      return `  readonly ${p.name}!: ${type};`;
    })
    .join('\n');

  const paramsVar = cls.hasFieldConfig ? 'resolved' : 'params';

  const fieldConfigBlock = cls.hasFieldConfig
    ? emitFieldConfigBlock(cls)
    : '';

  const assignments = cls.properties
    .map((p) => `    this.${p.name} = __freezedDeepFreeze(${paramsVar}.${p.name});`)
    .join('\n');

  const methods: string[] = [];
  if (cls.copyWith !== false) methods.push(emitWithGetter(cls));
  if (cls.equal !== false) methods.push(emitEqualsMethod(cls));
  methods.push(emitToStringMethod(cls));

  return `export abstract class ${cls.generatedClassName} {
${readonlyFields}

  constructor(params: ${cls.className}Params) {
${fieldConfigBlock}${assignments}
    Object.freeze(this);
  }

${methods.join('\n\n')}
}`;
}

function emitFieldConfigBlock(cls: ParsedFreezedClass): string {
  const lines = [
    `    const __options = (new.target as any)[Symbol.for('freezedts:options')];`,
    `    const __fields: Record<string, any> = __options?.fields ?? {};`,
    `    const resolved = { ...params } as Required<${cls.className}Params>;`,
    `    for (const [key, config] of Object.entries(__fields)) {`,
    `      if ('default' in config && (resolved as any)[key] === undefined) {`,
    `        (resolved as any)[key] = config.default;`,
    `      }`,
    `      if (config.assert && !config.assert((resolved as any)[key])) {`,
    "        throw new Error(config.message ?? `Assertion failed for '${new.target.name}.${key}'`);",
    `      }`,
    `    }`,
  ];
  return lines.join('\n') + '\n';
}

function emitWithGetter(cls: ParsedFreezedClass): string {
  return `  get with(): ${cls.className}With<this> {
    return __freezedWith(this);
  }`;
}

function emitToStringMethod(cls: ParsedFreezedClass): string {
  const parts = cls.properties
    .map((p) => `${p.name}: \${this.${p.name}}`)
    .join(', ');
  return `  toString(): string {
    return \`\${this.constructor.name}(${parts})\`;
  }`;
}

function emitEqualsMethod(cls: ParsedFreezedClass): string {
  const comparisons = cls.properties.map((p) => {
    if (cls.equalityMode === 'deep') {
      return `__freezedDeepEqual(this.${p.name}, other.${p.name})`;
    }
    if (p.isFreezed) {
      return `this.${p.name}.equals(other.${p.name})`;
    }
    return `this.${p.name} === other.${p.name}`;
  });

  const returnExpr = comparisons.length === 0
    ? 'true'
    : comparisons.join(' &&\n      ');

  return `  equals(other: unknown): boolean {
    if (this === other) return true;
    if (!(other instanceof ${cls.generatedClassName})) return false;
    return ${returnExpr};
  }`;
}
