import { describe, it, expect } from 'bun:test';
import { emitFreezedFile } from './emitter.js';
import type { ParsedFreezedClass } from './parser.js';

describe('emitFreezedFile', () => {
  it('generates header and deep copy helper', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];
    const output = emitFreezedFile(classes);
    expect(output).toContain('// generated by freezedts, do not edit');
    expect(output).toContain('const __freezedWith');
    expect(output).toContain("Symbol.for('freezedts:options')");
    expect(output).toContain('new Proxy');
  });

  it('generates a base class with readonly properties and Object.freeze', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        properties: [
          { name: 'firstName', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'lastName', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('export type PersonParams = {');
    expect(output).toContain('  firstName: string;');
    expect(output).toContain('  lastName: string;');
    expect(output).toContain('  age: number;');
    expect(output).toContain('export abstract class $Person {');
    expect(output).toContain('  readonly firstName!: string;');
    expect(output).toContain('  readonly lastName!: string;');
    expect(output).toContain('  readonly age!: number;');
    expect(output).toContain('  constructor(params: PersonParams) {');
    expect(output).toContain('    this.firstName = params.firstName;');
    expect(output).toContain('    Object.freeze(this);');
  });

  it('generates a With type and getter instead of with() method', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'age', type: 'number', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // With type — no @freezed properties, so simple callable
    expect(output).toContain('export type PersonWith<Self> = {');
    expect(output).toContain('  (overrides: Partial<PersonParams>): Self;');
    // Getter
    expect(output).toContain('get with(): PersonWith<this>');
    expect(output).toContain('return __freezedWith(this)');
    // Old method gone
    expect(output).not.toContain('with(overrides:');
  });

  it('generates With type with nested members for @freezed properties', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Inner',
        generatedClassName: '$Inner',
        hasFieldConfig: false,
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
      {
        className: 'Outer',
        generatedClassName: '$Outer',
        hasFieldConfig: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'inner', type: 'Inner', optional: false, hasDefault: false, isFreezed: true },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // Outer's With type includes inner chain
    expect(output).toContain('export type OuterWith<Self> = {');
    expect(output).toContain('  (overrides: Partial<OuterParams>): Self;');
    expect(output).toContain('  inner: InnerWith<Self>;');
    // Inner's With type has no nested members
    expect(output).toContain('export type InnerWith<Self> = {');
  });

  it('replaces @freezed property types with $ClassName in params and readonly', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Inner',
        generatedClassName: '$Inner',
        hasFieldConfig: false,
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
      {
        className: 'Outer',
        generatedClassName: '$Outer',
        hasFieldConfig: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'inner', type: 'Inner', optional: false, hasDefault: false, isFreezed: true },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    // Params type uses $Inner
    expect(output).toContain('  inner: $Inner;');
    // Readonly field uses $Inner
    expect(output).toContain('  readonly inner!: $Inner;');
  });

  it('marks optional params with ? in the params type', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Config',
        generatedClassName: '$Config',
        hasFieldConfig: false,
        properties: [
          { name: 'host', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'port', type: 'number', optional: true, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  host: string;');
    expect(output).toContain('  port?: number;');
    expect(output).toContain('  readonly port!: number;');
  });

  it('makes hasDefault properties optional in params type', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasFieldConfig: true,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'count', type: 'number', optional: false, hasDefault: true, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  name: string;');
    expect(output).toContain('  count?: number;');
  });

  it('generates field config processing block when hasFieldConfig is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasFieldConfig: true,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'count', type: 'number', optional: false, hasDefault: true, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain("Symbol.for('freezedts:options')");
    expect(output).toContain('const resolved = { ...params } as Required<CounterParams>;');
    expect(output).toContain("if ('default' in config");
    expect(output).toContain('config.assert');
    expect(output).toContain('this.name = resolved.name;');
    expect(output).toContain('this.count = resolved.count;');
  });

  it('omits processing block when hasFieldConfig is false', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Simple',
        generatedClassName: '$Simple',
        hasFieldConfig: false,
        properties: [
          { name: 'value', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).not.toContain('resolved');
    expect(output).toContain('this.value = params.value;');
  });

  it('strips | undefined from readonly type when hasDefault is true', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Counter',
        generatedClassName: '$Counter',
        hasFieldConfig: true,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'count', type: 'number | undefined', optional: true, hasDefault: true, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('  readonly count!: number;');
    expect(output).not.toContain('readonly count!: number | undefined');
    expect(output).toContain('  count?: number | undefined;');
  });

  it('generates multiple classes in one file', () => {
    const classes: ParsedFreezedClass[] = [
      {
        className: 'Person',
        generatedClassName: '$Person',
        hasFieldConfig: false,
        properties: [{ name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false }],
      },
      {
        className: 'Child',
        generatedClassName: '$Child',
        hasFieldConfig: false,
        properties: [
          { name: 'name', type: 'string', optional: false, hasDefault: false, isFreezed: false },
          { name: 'parentName', type: 'string', optional: false, hasDefault: false, isFreezed: false },
        ],
      },
    ];

    const output = emitFreezedFile(classes);
    expect(output).toContain('export abstract class $Person {');
    expect(output).toContain('export abstract class $Child {');
    expect(output).toContain('export type PersonParams = {');
    expect(output).toContain('export type ChildParams = {');
    expect(output).toContain('export type PersonWith<Self>');
    expect(output).toContain('export type ChildWith<Self>');
  });
});
