import { Project } from 'ts-morph';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { parseFreezedClasses } from './parser.js';
import { emitFreezedFile } from './emitter.js';
import { resolveClassOptions, DEFAULTS as DEFAULT_CONFIG } from './config.js';
import type { ResolvedConfig } from './config.js';

export interface GenerateResult {
  filesWritten: number;
  errors: string[];
  warnings: string[];
}

export function generate(filePaths: string[], config?: ResolvedConfig): GenerateResult {
  const project = new Project({
    skipAddingFilesFromTsConfig: true,
    compilerOptions: { strict: true },
  });

  const resolvedConfig = config ?? DEFAULT_CONFIG;

  let filesWritten = 0;
  const errors: string[] = [];
  const warnings: string[] = [];

  // Phase 1: Parse all files
  const parsed = new Map<string, { absolutePath: string; classes: ReturnType<typeof parseFreezedClasses>['classes'] }>();

  for (const filePath of filePaths) {
    const absolutePath = path.resolve(filePath);
    const sourceFile = project.addSourceFileAtPath(absolutePath);
    try {
      const { classes, warnings: parseWarnings } = parseFreezedClasses(sourceFile);
      for (const w of parseWarnings) {
        warnings.push(`${filePath}:${w.line}: ${w.message}`);
      }
      if (classes.length > 0) {
        parsed.set(filePath, { absolutePath, classes });
      }
    } catch (e) {
      errors.push(`${filePath}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  // Phase 2: Resolve isFreezed — mark properties whose type matches any
  // @freezed class name across all parsed files
  const classToFile = new Map<string, string>();
  for (const [filePath, { classes }] of parsed) {
    for (const cls of classes) {
      classToFile.set(cls.className, filePath);
    }
  }
  for (const [filePath, { absolutePath, classes }] of parsed) {
    for (const cls of classes) {
      for (const prop of cls.properties) {
        const baseType = prop.type.replace(/\s*\|\s*undefined$/, '').trim();
        const sourceFilePath = classToFile.get(baseType);
        if (sourceFilePath) {
          prop.isFreezed = true;
          if (sourceFilePath !== filePath) {
            const fromAbsolute = parsed.get(sourceFilePath)!.absolutePath;
            const relativePath = path.relative(
              path.dirname(absolutePath),
              fromAbsolute.replace(/\.ts$/, '.freezed.js'),
            );
            prop.importFrom = relativePath.startsWith('.')
              ? relativePath.replace(/\\/g, '/')
              : './' + relativePath.replace(/\\/g, '/');
          }
        }
      }
    }
  }

  // Phase 3: Resolve generation options — merge per-class with config defaults
  for (const { classes } of parsed.values()) {
    for (const cls of classes) {
      const resolved = resolveClassOptions(cls, resolvedConfig);
      cls.copyWith = resolved.copyWith;
      cls.equal = resolved.equal;
    }
  }

  // Phase 4: Emit and write
  for (const [filePath, { absolutePath, classes }] of parsed) {
    try {
      let output = emitFreezedFile(classes);

      // Collect cross-file imports
      const imports = new Map<string, Set<string>>();
      for (const cls of classes) {
        for (const prop of cls.properties) {
          if (prop.isFreezed && prop.importFrom) {
            if (!imports.has(prop.importFrom)) imports.set(prop.importFrom, new Set());
            const symbols = imports.get(prop.importFrom)!;
            symbols.add(`$${prop.type.replace(/\s*\|\s*undefined$/, '').trim()}`);
            symbols.add(`${prop.type.replace(/\s*\|\s*undefined$/, '').trim()}Params`);
            if (cls.copyWith !== false) {
              symbols.add(`${prop.type.replace(/\s*\|\s*undefined$/, '').trim()}With`);
            }
          }
        }
      }
      if (imports.size > 0) {
        const importLines = [...imports.entries()]
          .map(([importPath, symbols]) =>
            `import { ${[...symbols].join(', ')} } from '${importPath}';`,
          )
          .join('\n');
        output = output.replace(
          '// generated by freezedts, do not edit\n',
          `// generated by freezedts, do not edit\n\n${importLines}\n`,
        );
      }

      if (resolvedConfig.format) {
        output = formatOutput(output);
      }
      const outputPath = absolutePath.replace(/\.ts$/, '.freezed.ts');
      fs.writeFileSync(outputPath, output, 'utf-8');
      filesWritten++;
    } catch (e) {
      errors.push(`${filePath}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  return { filesWritten, errors, warnings };
}

const formatProject = new Project({ useInMemoryFileSystem: true });

function formatOutput(code: string): string {
  const existing = formatProject.getSourceFile('format.ts');
  if (existing) formatProject.removeSourceFile(existing);
  const file = formatProject.createSourceFile('format.ts', code);
  file.formatText();
  return file.getFullText();
}
